#---------------------------
# Material-T
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: http://cdn.pfish.xyz/pic/20190126/ufc14qxxttQM.png?imageslim
apple_touch_icon: http://cdn.pfish.xyz/pic/20190126/hIIQ7WHb9VBV.png

#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  subtitle:
    enable: true
  head_img: http://cdn.pfish.xyz/pic/20190126/bcYYhAKkFVXi.JPG

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    enable: true
    list:
      archives: /archives/
      about: /about/
  icons:
    enable: true
    # tips: 'See me here'
    list: 
      github: https://github.com/PFISH1998
      weibo: https://weibo.com/u/5063744248
      twitter: 
  

#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  head_img: ../img/post-head.jpg
  comments_type: 'disqus'
  disqus: 
    shortname:
  toc: 
    enable: true

# Code Highlight
# Theme available: github | tomorrow-night | tomorrow | tomorrow-night-eighties
highlight:
  enable: true
  theme: github

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  head_img: http://cdn.pfish.xyz/pic/20190126/VQqSjdKyLNer.JPG

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  head_img: http://cdn.pfish.xyz/pic/20190116/ue8EPY0rkKcI.JPG
  avatar: http://cdn.pfish.xyz/pic/20190116/zuts8XrRkm7h.jpeg?imageslim
  name: PFISH
  job: a student
  introduce: CODE / PICTURE / LIFE
  extension:

about_icons: 
  github: https://github.com/PFISH1998
  weibo: https://weibo.com/u/5063744248
  twitter: 

#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <b>Hello World</b>
