#---------------------------
# Material-T
# 一款Material Design风格的HEXO主题
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: http://cdn.pfish.xyz/pic/20190116/6LuHHSdCAU6U.png?imageslim
apple_touch_icon: http://cdn.pfish.xyz/pic/20190116/Bb28gqNcpNKm.png?imageslim


#---------------------------
# 首页
# Index Page
#---------------------------
subtitle:
  enable: true

index_head_img: https://i.loli.net/2018/10/13/5bc1af44bb064.jpg 

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
menu:
  enable: true
  list:
    archives: /archives/
    about: /about/
  

social_icons:
  enable: true
  tips: 'See me here'
  list: 
    github: https://github.com/PFISH1998
    weibo: https://weibo.com/u/5063744248
    twitter: 
  

#---------------------------
# 文章页
# Post Page
#---------------------------
comments_type: 'disqus'
disqus: 
  shortname:

toc: 
  enable: true

# Code Highlight
# Theme available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
highlight:
  enable: false
  theme: tomorrow-night-eighties
  line_number: false
  auto_detect: false
  tab_replace:

  
#---------------------------
# 归档页
# Archive Page
#---------------------------
archive_head_img: http://cdn.pfish.xyz/pic/20190116/3hyL7kWcVKrO.jpg?imageslim

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  head_img: http://cdn.pfish.xyz/pic/20190116/ue8EPY0rkKcI.JPG
  avatar: http://cdn.pfish.xyz/pic/20190116/zuts8XrRkm7h.jpeg?imageslim
  name: PFISH
  job: a student
  introduce: CODE / PICTURE / LIFE
  extension:

about_icons: 
  github: https://github.com/PFISH1998
  weibo: https://weibo.com/u/5063744248
  twitter: 


#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <b>Hello World</b>